version: '3.8'

services:
  # Service 1: The Web Server (Django)
  web:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Live Sync: Changes on your PC show up in Docker instantly
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=subtracker
      - DB_USER=postgres
      - DB_PASS=supersecretpassword

  # Service 2: The Background Worker (Celery)
  worker:
    build: .
    env_file:
      - .env
    # Note: On Linux/Docker, we don't need 'eventlet'. Standard config works!
    command: celery -A SubTracker worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=subtracker
      - DB_USER=postgres
      - DB_PASS=supersecretpassword

  # Service 3: The Database (PostgreSQL)
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=subtracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 4: The Broker (Redis)
  redis:
    image: redis:7-alpine

    # Service 5: The Scheduler (Celery Beat)
# Service 5: The Scheduler (Celery Beat)
  beat:
    build: .
    env_file:
      - .env
    command: celery -A SubTracker beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=subtracker
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./certbot/conf:/etc/letsencrypt    # Shared folder for Keys
      - ./certbot/www:/var/www/certbot      # Shared folder for Validation
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt    # Shared folder for Keys
      - ./certbot/www:/var/www/certbot



volumes:
  postgres_data:
