# Generated by Django 6.0 on 2026-01-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reminder_days_before',
            field=models.IntegerField(default=3, help_text='Days before to notify'),
        ),
    ]
